import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import { Inter } from "next/font/google";
import { boy_stands_on_the_top_of_a_mountain } from "@/assets";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>NftMarketplace</title>

        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex justify-center">
        <div className="w-[70%] flex">
          <div className="flex-1">
            <Image
              src={boy_stands_on_the_top_of_a_mountain}
              className="rounded-3xl"
            />
          </div>
          <div className="flex-1 flex flex-col items-center justify-center">
            <h1 className="text-blue-600 font-extrabold text-6xl text-center">
              Explore the World of NFTs!
            </h1>

            <button className="rounded-full bg-white hover:bg-blue-600 text-blue-600 hover:text-white text-4xl font-bold py-2 px-3 mt-10 border-2">
              <Link href="/marketplace">NFT Marketplace</Link>
            </button>
          </div>
        </div>
      </main>
    </>
  );
}
